name: 'Run container'
description: 'Run the wanted container'
inputs:
  image-name:
    description: 'The description of the image'
    required: true
    default: 'docker.pkg.github.com/aboulay/kata-roman/kata-roman'
  commit-short-sha:  # id of input
    description: 'The sha of the commit'
    required: true
    default: 'latest'
runs:
  using: 'docker'
  image: 'docker.pkg.github.com/aboulay/kata-roman/kata-roman'