name: 'Run container'
description: 'Run the wanted container'
inputs:
  number:
    description: 'The number to check'
    required: true
    default: '1'
runs:
  using: 'docker'
  image: 'docker.pkg.github.com/aboulay/kata-roman/kata-roman'
  args:
    - ${{ inputs.number }}